# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: rails
  timeout: 5000
  reaping_frequency: 30

development:
  <<: *default
  database: grademade_development
  password: <%= Rails.application.secrets[:database][:password] %>

test:
  <<: *default
  database: grademade_test
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  database: grademade_production
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>
